# dev,test,prod等优先,common通用
[common]
# 为避免与php发生冲突,SERVER_ID 从512开始-1023,PHP则从0-63计算
server_id = 512
[common.server]
# 用于侦听和注册到consul服务器
http_host = ""
http_port = 8341
grpc_host = ""
grpc_port = 9341
# 单机版时有意义,分布式用emqx替代
websocket_host = ""
websocket_port = 7341


[common.db]
# mysql 部分
connection = "mysql"
host = "192.168.0.1"
port = 3306
database = "base"
username = "root"
password = "123123"
timezone = "+08:00"
max_idle = 5
max_open = 50

[common.redis]
# redis 部分
uri = "127.0.0.1:6937"
auth = "123123"
db = 1
max_active = 50
max_idle = 5
time_out = 10

[common.queue]
# 队列部分
# 前缀
prefix = "wego"
# 侦听队列
listen = ["demo1"]
#扫描频率,分钟
interval = 1
# 并发
concurrency = 10

[common.cache]
# 缓存设置 100*1024*1024
size = 104857600

[common.mqtt]
host = "tcp://127.0.0.1:1883"
username = ""
password = ""
parallel = true



[dev.server]
http_port = 8342
[dev.db]
host = "127.0.0.1"


[prod.db]
host = "123.123.123.123"